### PR TITLE
Added corridors from https://github.com/cns-iu/3d-corridor/tree/main/…

### PR DESCRIPTION
**Pull request by andreasbueckle**
…corridor_models_hra_pop_glb

### CODE REVIEW

**Comment by bherr2** [comment]
Replace deprecated_corridors. Don't put it in input_data

**Comment by bherr2** [comment]
This is still a deprecated method until we can run / generate corridors on our own via API or CLI.

**Comment by bherr2** [comment]
*deprecated-corridors that is

**Comment by andreasbueckle** [comment]
Done, moved corridors to ```deprecated_corridors```

**Pull request merged**
